version: '3.8'

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    ports:
      - '5678:5678'
    environment:
      - N8N_PORT=5678
      - NODE_ENV=production
      - N8N_PROTOCOL=https # Use HTTPS
      - N8N_HOST=${COOLIFY_FQDN}
      - WEBHOOK_URL=https://${COOLIFY_FQDN}/ # Use HTTPS here too
      - GENERIC_TIMEZONE=UTC
    volumes:
      - n8n_data:/home/node/.n8n
    restart: unless-stopped

volumes:
  n8n_data:
    driver: local
